apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://gitlab.yunwei.edu/"
      token = "7ad8473fe169d42f232d59e4ea9910"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        privileged = true
      [[runners.kubernetes.volumes.host_path]]
        name = "docker-sock"
        mount_path = "/var/run/docker.sock"
        host_path = "/var/run/docker.sock"
      [[runners.kubernetes.volumes.host_path]]
        name = "kubectl"
        mount_path = "/usr/bin/kubectl"
        host_path = "/usr/bin/kubectl"
      [[runners.kubernetes.volumes.host_path]]
        name = "kubectl-conf"
        mount_path = "/etc/kubernetes/admin.conf"
        host_path = "/root/.kube/config"