apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://gitlab.yunwei.edu/"
      token = "7ad8473fe169d42f232d59e4ea9910"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "192.168.31.140:5000/centos:latest"