#!/usr/bin/bash
#
func_prepare(){
	fab -H $IPS -f fab_chk.py prepare -u $REMOTE_USER -P $COLLOR
}

func_cpuidle(){
	fab -H $IPS -f fab_chk.py cpuidle -u $REMOTE_USER -P $COLLOR|grep -P "out:.*[0-9]"
}

func_mem(){
	fab -H $IPS -f fab_chk.py mem -u $REMOTE_USER -P $COLLOR|grep -P "out:.*Mem"
}

func_rootrate(){
	fab -H $IPS -f fab_chk.py rootrate -u $REMOTE_USER -P $COLLOR|grep -P "out:.*G|T"
}

func_sn(){
	fab -H `echo $PHY_HOSTS|sed 's/ /,/g'` -f fab_chk.py prepare -u $REMOTE_USER -P $COLLOR  #for test
	fab -H `echo $PHY_HOSTS|sed 's/ /,/g'` -f fab_chk.py sn -u $REMOTE_USER -P $COLLOR
}

func_diskerr(){
	fab -H `echo $PHY_HOSTS|sed 's/ /,/g'` -f fab_chk.py diskerr -u $REMOTE_USER -P $COLLOR
}
